### PR TITLE
Put a space between the day and the time

### PR DESCRIPTION
**Pull request by burz**
I think that this is a bit more readable.

### CODE REVIEW

**Comment by tony** [comment]
There should already be a space between day and time, I believe. Can you show me a screenshot of what you see?

Here is my before / after:

screen shot 2015-10-23 at 5 34 15 pm
screen shot 2015-10-23 at 5 34 21 pm

**Comment by burz** [comment]
The problem is that the locations of each individual item in
```
2:34 Fri 5:34:21 PM 2015-10-23
```
appear to be static. I'll try to get a screenshot later tonight, but the problem is when the hour has two digits. For instance, if it were 6 hours later, it would appear as
```
2:34 Fri11:34:21 PM 2015-10-23
```
Perhaps there is another way to solve this problem besides the extra space? Maybe like a format with two places for digits?

**Comment by tony** [comment]
Which OS is this on by the way?  When I tried it it ended up creating an extra space on my systems (OS X and FreeBSD)

There was a rebase a few weeks ago.

Assuming ``tony`` is the remote of this repo (if not, ``git remote add tony https://github.com/tony/tmux-config.git``)

Can you run ``git pull --rebase tony master``, resolve the conflicts if any and ``git push --force``?

**Comment by tony** [comment]
@curz: Any update on this? Can you rebase?

**Comment by tony** [comment]
@burz: Any update on this? Can you rebase?

**Comment by tony** [comment]
I am going to close this for now. I need this to be rebased.

If you're still interested in this @burz, feel free to reopen.

**Pull request closed without merging**
